2017-12-17 11:28:48,562 : Machine : Mission Pinball Framework Core Engine v0.33.48
2017-12-17 11:28:48,562 : Machine : Command line arguments: {'loglevel': 11, 'consoleloglevel': 20, 'logfile': 'logs\\2017-12-17-11-28-48-mpf-MSI.log', 'force_assets_load': False, 'mpfconfigfile': 'c:\\python34\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'bcp': True, 'force_platform': None, 'no_load_cache': False, 'pause': False, 'mc_file_name': None, 'create_config_cache': True, 'configfile': ['config'], 'syslog_address': None}
2017-12-17 11:28:48,562 : Machine : MPF path: c:\python34\lib\site-packages\mpf
2017-12-17 11:28:48,562 : Machine : Machine path: C:\GIT\Escape_Pinball
2017-12-17 11:28:48,562 : Machine : Platform: win32
2017-12-17 11:28:48,562 : Machine : Python executable location: c:\python34\python.exe
2017-12-17 11:28:48,562 : Machine : Python version: 3.4.4 (64-bit)
2017-12-17 11:28:48,838 : Machine : Loading config from original files
2017-12-17 11:28:48,914 : Machine : Machine config file #1: C:\GIT\Escape_Pinball\config\config
2017-12-17 11:28:49,122 : Machine : Config file cache created: C:\Users\Jim\AppData\Local\Temp\fe94515d23647c6740272514cfb07204config
2017-12-17 11:28:49,154 : root : Could not import "pinproc". Most likely you do not have libpinproc and/or pypinproc installed. You can run MPF in software-only "virtual" mode by using the -x command like option for now instead.
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\mpf\commands\game.py", line 181, in __init__
    MachineController(mpf_path, machine_path, vars(args)).run()
  File "c:\python34\lib\site-packages\mpf\core\machine.py", line 117, in __init__
    self._load_hardware_platforms()
  File "c:\python34\lib\site-packages\mpf\core\machine.py", line 534, in _load_hardware_platforms
    self.add_platform(platform)
  File "c:\python34\lib\site-packages\mpf\core\machine.py", line 647, in add_platform
    hardware_platform(self))
  File "c:\python34\lib\site-packages\mpf\platforms\p_roc.py", line 38, in __init__
    super(HardwarePlatform, self).__init__(machine)
  File "c:\python34\lib\site-packages\mpf\platforms\p_roc_common.py", line 53, in __init__
    raise AssertionError('Could not import "pinproc". Most likely you do not '
AssertionError: Could not import "pinproc". Most likely you do not have libpinproc and/or pypinproc installed. You can run MPF in software-only "virtual" mode by using the -x command like option for now instead.
